### PR TITLE
Quick workaround fix for issue when USB modules are not loaded automaticall

### PR DESCRIPTION
**Pull request by maxsteciuk**
Please see the following ticket for more details: https://github.com/project-trident/trident-core/issues/63

### CODE REVIEW

**Comment by q5sys** [comment]
how many varied systems have you tested this on?

**Comment by q5sys** [comment]
Obviously we don't want to commit anything that fixes one systems problem, but breaks 5 other systems.

**Comment by maxsteciuk** [comment]
Trident and legacy TrueOS desktop

TrueOS desktop had FreeBSD 12-CURRENT early March build  and does not have this issue because the legacy /etc/devd/usb.conf is used there
Trident with later FreeBSD build where /etc/devd/usb.conf was replaced does have an issue where modules are not loaded automatically and devmatch does not pick them up.


But this loader.conf.local file is local to Trident as per this comment? What other variations should we account for?
> # This file is installed by Project Trident
> # Changes to this file will be lost during updates
>  This  well it is broken already
> 

Also here is what happens if USB device is selected as default and sysctl complains on startup:
```
 * Configuring kernel parameters ...
sysctl: hw.snd.default_unit=7: Invalid argument
```

**Comment by q5sys** [comment]
i see you've got the ticket upstream with FreeBSD, we'll probably want to hold off and see what their thoughts are on it, as they're way more knowledgeable about how that works than we are.  And since we havent gotten reports of this from a bunch of other people; it seems isolated at this point.

**Comment by q5sys** [comment]
👍 Yea this definitely needs to be documented so if anyone else runs into it, they can get the fix.  I'd love to ship this, but we want to make sure that this is the actual problem and that your fix isn't masking the real issue which ultimately needs to be resolved.

**Comment by beanpole135** [comment]
Closing stale PR.
Appears to be getting worked on by upstream FreeBSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235257

**Pull request closed without merging**
